CREATE DATABASE IF NOT EXISTS GL;
USE GL;

SHOW TABLES;
CREATE TABLE employee(Id INT, Name VARCHAR(50) NOT NULL, Email_Id VARCHAR(50) NOT NULL, Phone_Number VARCHAR(15), PRIMARY KEY(Id));
SHOW TABLES;
DESC employee;

SELECT * FROM employee;



